config/routes.rb
Calendar::Application.routes.draw do

  resources :attendances

  get "home/page"
  root :to => 'home#pages'
  resources :users
  resources :attendances
  resources :categories
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    get 'logout_for_day' => :logout_for_day
  end

   root :to => 'welcome#index'

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  attr_accessible :login, :logout, :user_id
  belongs_to :user
  has_many :recesses, through: :user
  
   def start_time
    login
   end
   def title
     ress =Time.at(recess_time.to_i).utc.strftime("%H:%M:%S")
    "#{user.email.split('@')[0]},  : #{hours_for_day} hrs, Recess :#{recess_time} "
   end
   def hours_for_day(date = login)
     end_time = logout || start_time
     Time.at(end_time-login).utc.strftime("%H:%M")
   end
   def recess_time
    recesses.where("user_id = ?", user).select([:r_start, :r_stop]).map { |u| ((u.r_stop || u.r_start)-u.r_start) }.inject(:+)
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  load_and_authorize_resource
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendances }
    end
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
      if current_user and admin?
      @events = Attendance.all
      
    else 
       @events = current_user.attendences.all
    end 
    @attendance = Attendance.find(params[:id])
  end
  def new
    @attendance = Attendance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendance }
    end
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(params[:attendance])

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render json: @attendance, status: :created, location: @attendance }
      else
        format.html { render action: "new" }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendances/1
  # PUT /attendances/1.json
  def update
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      if @attendance.update_attributes(params[:attendance])
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= simple_form_for(@attendance) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :login %>
    <%= f.input :logout %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <tr>
    <th>User</th>
    <th>Login</th>
    <th>Logout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.user_id %></td>
    <td><%= attendance.login %></td>
    <td><%= attendance.logout %></td>
    <td><%= link_to 'Show', attendance %></td>
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @attendance.user_id %>
</p>

<p>
  <b>Login:</b>
  <%= @attendance.login %>
</p>

<p>
  <b>Logout:</b>
  <%= @attendance.logout %>
</p>
<%= calendar @events do |event| %>
  <div><%= link_to event.title, event %></div>
<% end %>
<br/>
<br/>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>